main: carslo.mods.custom_content_api.CustomContentAPI

name: CustomContentAPI
author: [Carslo_45]
version: 0.1
api-version: 1.21.4

depends: [Kotlin]

commands:
  test:
    description: Test some stuff
    permission: custom_content_api.commands.test
