name: Documentation Improvement
description: Request improvements to the Documentation
title: "[Docs]: "
labels: ["documentation"]
assignees:
  - Cardlo45

body:
  - type: textarea
    id: what
    attributes:
      label: Describe the Change
      description: Explain what should be changed
      placeholder: Add X to Y
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Reason
      description: Explain why this should be changed
      placeholder: Add X to Y
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Additional information you want to tell us. (Optional)
      placeholder: This would solve #9999
    validations:
      required: false
  - type: checkboxes
    id: confirm
    attributes:
      label: Additional checks
      description: Please check the following.
      options:
        - label: I checked if there isn't already a issue for a similar change.
          required: true