name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: mvn install -f pom.xml
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/*.jar
          draft: true
          token: ${{ github.token }}
